services:
  - type: web
    name: fsd-project2-api
    runtime: node
    autoDeployTrigger: commit
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: JWT_SECRET
        generateValue: true